# Generated by Django 3.1.7 on 2021-03-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('ELECTRONICS', 'ELECTRONICS'), ('PETS/ANIMALS', 'PETS/ANIMALS'), ('ACCESSORIES', 'ACCESSORIES')], default='ACCESSORIES', max_length=50, null=True),
        ),
    ]
