# Generated by Django 3.1.7 on 2021-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210313_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reward',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
