# Generated by Django 3.1.7 on 2021-03-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210313_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claims',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
