# Generated by Django 3.1.7 on 2021-03-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210313_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_category',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='claims',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('PETS/ANIMALS', 'PETS/ANIMALS'), ('ACCESSORIES', 'ACCESSORIES')], default='ACCESSORIES', max_length=50),
        ),
    ]
